### ISSUE TITLE
Email link should get recipient address from back-end mail.from.address

### ISSUE THREAD

**Issue by lieszkol** [skydiver/october-plugin-ssbuttons#1]
Currently the plugin does not set any recipient for the generated mailto:: link. Perhaps this could be a new setting for the plugin, or the default sender set in the OctoberCMS back end.

I am using the latter and have modified SSButtonsSSB.php OnRender and added:
`$this->page['email'] = Config::get('mail.from.address');`

(also added `use Config;` to the includes)

and changed ssbuttonssb/default.htm mailto line as follows:
`...<a href="mailto:{{ email }}?subject=...`

I'm sure there is a better approach.

**Comment by skydiver** [comment]
But the "from address" will depends on the visitor, it's a dynamic attribute, do you agree?

**Comment by lieszkol** [comment]
Ah - I see what you mean :-) the intent of the button is for the user to send an email about the website to one of his friends. I assumed that the intent of the button is to contact the website owner! So I was talking about the recipient address, not the sender. 

Never mind, and thanks again for the great little plugin!
