### ISSUE TITLE
Order share buttons 

### ISSUE THREAD

**Issue by xseguib** [skydiver/october-plugin-ssbuttons#3]
Would be nice to have an option to order the buttons.

**Comment by skydiver** [comment]
There isn't a sort field on the component inspector, so ... this is the best solution i can imagine ... what do you think?


![screenshot from 2016-11-19 20-26-16](https://cloud.githubusercontent.com/assets/578784/20459156/9581b3a8-ae96-11e6-8704-72de3e4489c7.png)

**Comment by skydiver** [comment]
There isn't a sort field on the component inspector, so ... this is the best solution i can imagine ... what do you think?

![screenshot from 2016-11-19 20-29-00](https://cloud.githubusercontent.com/assets/578784/20459164/dea751a0-ae96-11e6-84ad-d11a11f176af.png)

**Comment by skydiver** [comment]
Added custom buttons order
