### ISSUE TITLE
JS for title is broken in some of the Buttons like the Email button

### ISSUE THREAD

**Issue by Verbat** [skydiver/october-plugin-ssbuttons#5]
I just noticed a small error if you're using the SimpleSharingButtons with the option "use JS for title".
If there are two occurences of the titles (like in the email button) only the first title will be replaced. The second occurence still shows ___title___

In ssbuttons.js  you're using item.href = item.href.replace('___title___', encodeURI(title));
For now i fixed it with using a regexp with the g option.
item.href = item.href.replace(/\___title___/g,encodeURI(title));

Thanks

**Comment by skydiver** [comment]
Thanks @Verbat 
This was fixed on 0c77b4477a84b5707425977f3ea4802d3178983b
