### ISSUE TITLE
Not working with Blog Posts

### ISSUE THREAD

**Issue by FasTraxPOS** [skydiver/october-plugin-ssbuttons#7]
Not sharing correct URL with RainLab Blog plugin.

URL being shared is "/blog/post/:slug"
and not actual URL.

**Comment by FasTraxPOS** [comment]
SSButtons.php
SSButtonsNB.php
SSButtonsSSB.php

Change line 34 to             
$url   = ($this->properties['js']) ? '___url___'   : url($this->currentPageUrl());

Now works with blog posts also

**Comment by sean-ciaschi** [comment]
This `$url = ($this->properties['js']) ? 'url' : url($this->currentPageUrl());` where 'url' is, needs to stay as '___url___' since it'll affect the JS enabled function of the plugin.

use this: `$url   = ($this->properties['js']) ? '___url___'   : url($this->currentPageUrl());`

**Comment by skydiver** [comment]
This was fixed on version 1.3.0

Thanks for your help!
